"""Zixue (自学) FastAPI backend.

Endpoints:
  POST /generate      Generate (or look up) a bilingual weekly study plan.
  GET  /plans         List every plan in the shared library.
  GET  /plans/{id}    Fetch one stored plan in full.
  GET  /leaderboard   Universities ranked by contribution count.

Cost model: a plan is generated by calling the model API exactly once per
course. The result is stored in a shared library (SQLite). Any later request
for the same course is served from the library for free — no API call. Set
`force_regenerate=true` to bypass the library and generate a fresh plan.

Uploaded PDFs are never persisted: each is read into memory, parsed, and
discarded within the request. Only the generated *plan text* is stored.
"""

from __future__ import annotations

import os

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

import db
from agent import generate_plan
from parser import extract_text

VALID_DOC_TYPES = {"syllabus", "past exam", "lecture notes"}

app = FastAPI(
    title="Zixue (自学)",
    description="AI-powered study plan generator for international students.",
    version="0.2.0",
)

_origins = os.environ.get(
    "ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:3000"
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in _origins.split(",") if o.strip()],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def _startup() -> None:
    db.init_db()


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


def _truthy(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "on"}


@app.post("/generate")
async def generate(
    university: str = Form(...),
    course_code: str = Form(...),
    course_name: str = Form(...),
    department: str = Form(""),
    professor: str = Form(""),
    semester: str = Form(""),
    contributor: str = Form(""),
    force_regenerate: str = Form("false"),
    files: list[UploadFile] = File(default=[]),
    file_types: list[str] = Form(default=[]),
) -> dict:
    """Generate a plan, or serve an existing one from the library.

    Returns JSON:
      {
        "plan": <markdown>,
        "contributor": <str>,
        "cached": <bool>,        # true => served from library, no API call
        "plan_id": <int>,
        "university": <str>, "course_code": <str>, "course_name": <str>
      }
    """
    course = {
        "university": university,
        "course_code": course_code,
        "course_name": course_name,
        "department": department,
        "professor": professor,
        "semester": semester,
    }

    # Library hit short-circuits before we touch the uploaded files or the API.
    if not _truthy(force_regenerate):
        existing = db.find_plan_by_course(university, course_code, course_name)
        if existing:
            return {
                "plan": existing["plan"],
                "contributor": existing["contributor"] or "",
                "cached": True,
                "plan_id": existing["id"],
                "university": existing["university"],
                "course_code": existing["course_code"],
                "course_name": existing["course_name"],
            }

    # Library miss (or forced) — parse uploads in memory and call the model.
    documents: list[dict] = []
    for index, upload in enumerate(files):
        raw = await upload.read()
        if not raw:
            continue
        try:
            text = extract_text(raw)
        except ValueError as exc:
            raise HTTPException(
                status_code=400,
                detail=f"Failed to parse '{upload.filename}': {exc}",
            ) from exc
        finally:
            del raw

        label = file_types[index] if index < len(file_types) else "lecture notes"
        if label not in VALID_DOC_TYPES:
            label = "lecture notes"

        documents.append(
            {
                "label": label,
                "filename": upload.filename or f"document-{index + 1}.pdf",
                "text": text,
            }
        )

    try:
        plan = generate_plan(course, documents)
    except RuntimeError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(
            status_code=502, detail=f"Study plan generation failed: {exc}"
        ) from exc

    plan_id = db.insert_plan(course, contributor, plan)
    return {
        "plan": plan,
        "contributor": contributor,
        "cached": False,
        "plan_id": plan_id,
        "university": university,
        "course_code": course_code,
        "course_name": course_name,
    }


@app.get("/plans")
def list_plans() -> dict:
    return {"plans": db.list_plans()}


@app.get("/plans/{plan_id}")
def get_plan(plan_id: int) -> dict:
    plan = db.get_plan(plan_id)
    if not plan:
        raise HTTPException(status_code=404, detail="Plan not found")
    return plan


@app.get("/leaderboard")
def leaderboard() -> dict:
    return {"leaderboard": db.leaderboard()}
