import ReactMarkdown from "react-markdown";

const styles = {
  wrapper: {
    marginTop: "2rem",
    background: "#fff",
    border: "1px solid #e5e5e5",
    borderRadius: 12,
    padding: "1.75rem 2rem",
    lineHeight: 1.6,
  },
  badge: {
    display: "inline-block",
    fontSize: "0.78rem",
    fontWeight: 600,
    borderRadius: 999,
    padding: "0.2rem 0.7rem",
    marginBottom: "1rem",
  },
  cached: { background: "#e8f5e9", color: "#2e7d32" },
  fresh: { background: "#e3f2fd", color: "#1565c0" },
  credit: {
    marginTop: "2rem",
    paddingTop: "1rem",
    borderTop: "1px solid #eee",
    textAlign: "center",
    color: "#777",
    fontSize: "0.9rem",
  },
};

export default function PlanDisplay({ plan, contributor, cached }) {
  return (
    <article style={styles.wrapper}>
      <span
        style={{ ...styles.badge, ...(cached ? styles.cached : styles.fresh) }}
      >
        {cached
          ? "📚 From the library — no API used / 来自合集,未消耗 API"
          : "✨ Freshly generated / 新生成"}
      </span>
      <ReactMarkdown>{plan}</ReactMarkdown>
      <div style={styles.credit}>
        {contributor
          ? `📚 Contributed by @${contributor} — thank you for closing the information gap! / 感谢 @${contributor} 的贡献!`
          : "📚 Generated by Zixue (自学)."}
      </div>
    </article>
  );
}
