import ReactMarkdown from "react-markdown";

const styles = {
  wrapper: {
    marginTop: "2rem",
    background: "#fff",
    border: "1px solid #e5e5e5",
    borderRadius: 12,
    padding: "1.75rem 2rem",
    lineHeight: 1.6,
  },
  credit: {
    marginTop: "2rem",
    paddingTop: "1rem",
    borderTop: "1px solid #eee",
    textAlign: "center",
    color: "#777",
    fontSize: "0.9rem",
  },
};

export default function PlanDisplay({ plan, contributor }) {
  return (
    <article style={styles.wrapper}>
      <ReactMarkdown>{plan}</ReactMarkdown>
      <div style={styles.credit}>
        {contributor
          ? `📚 Contributed by @${contributor} — thank you for closing the information gap!`
          : "📚 Generated by Zixue (自学)."}
      </div>
    </article>
  );
}
